"""initial migration

Revision ID: bb699075faa1
Revises: 
Create Date: 2025-11-18 10:50:54.731161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb699075faa1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('total_lines', sa.Integer(), nullable=False),
    sa.Column('code_lines', sa.Integer(), nullable=False),
    sa.Column('complexity', sa.Integer(), nullable=False),
    sa.Column('num_functions', sa.Integer(), nullable=False),
    sa.Column('num_classes', sa.Integer(), nullable=False),
    sa.Column('num_imports', sa.Integer(), nullable=False),
    sa.Column('functions_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis')
    # ### end Alembic commands ###
